import { v } from "convex/values";

export const seasonValidator = v.object({
  id: v.string(),
  name: v.string(),
  startDate: v.string(),
  endDate: v.string(),
});

export const seasonPlayerLeaderValidator = v.object({
  playerId: v.id("players"),
  playerName: v.string(),
  photoUrl: v.optional(v.string()),
  clubId: v.id("clubs"),
  clubName: v.string(),
  gamesPlayed: v.number(),
  points: v.number(),
  rebounds: v.number(),
  assists: v.number(),
  steals: v.number(),
  blocks: v.number(),
  pointsPerGame: v.number(),
  reboundsPerGame: v.number(),
  assistsPerGame: v.number(),
  stealsPerGame: v.number(),
  blocksPerGame: v.number(),
});

export const seasonTeamLeaderValidator = v.object({
  clubId: v.id("clubs"),
  clubName: v.string(),
  gamesPlayed: v.number(),
  statGamesPlayed: v.number(),
  wins: v.number(),
  losses: v.number(),
  winPct: v.number(),
  pointsForPerGame: v.number(),
  pointsAllowedPerGame: v.number(),
  reboundsPerGame: v.number(),
  assistsPerGame: v.number(),
  stealsPerGame: v.number(),
  blocksPerGame: v.number(),
});

export const seasonPlayerStatsRowValidator = v.object({
  playerId: v.id("players"),
  playerName: v.string(),
  photoUrl: v.optional(v.string()),
  clubId: v.id("clubs"),
  clubName: v.string(),
  clubNickname: v.optional(v.string()),
  gamesPlayed: v.number(),
  starts: v.number(),
  minutes: v.number(),
  minutesPerGame: v.number(),
  points: v.number(),
  pointsPerGame: v.number(),
  rebounds: v.number(),
  reboundsPerGame: v.number(),
  assists: v.number(),
  assistsPerGame: v.number(),
  steals: v.number(),
  stealsPerGame: v.number(),
  blocks: v.number(),
  blocksPerGame: v.number(),
  turnovers: v.number(),
  turnoversPerGame: v.number(),
  personalFouls: v.number(),
  personalFoulsPerGame: v.number(),
  plusMinus: v.number(),
  plusMinusPerGame: v.number(),
  fieldGoalsMade: v.number(),
  fieldGoalsAttempted: v.number(),
  fgPct: v.number(),
  threePointersMade: v.number(),
  threePointersAttempted: v.number(),
  threePct: v.number(),
  freeThrowsMade: v.number(),
  freeThrowsAttempted: v.number(),
  ftPct: v.number(),
});

export const seasonTeamStatsRowValidator = v.object({
  clubId: v.id("clubs"),
  clubName: v.string(),
  clubNickname: v.optional(v.string()),
  clubLogoUrl: v.optional(v.string()),
  gamesPlayed: v.number(),
  statGamesPlayed: v.number(),
  wins: v.number(),
  losses: v.number(),
  winPct: v.number(),
  pointsFor: v.number(),
  pointsAgainst: v.number(),
  pointsForPerGame: v.number(),
  pointsAllowedPerGame: v.number(),
  rebounds: v.number(),
  reboundsPerGame: v.number(),
  assists: v.number(),
  assistsPerGame: v.number(),
  steals: v.number(),
  stealsPerGame: v.number(),
  blocks: v.number(),
  blocksPerGame: v.number(),
  turnovers: v.number(),
  turnoversPerGame: v.number(),
  fieldGoalsMade: v.number(),
  fieldGoalsAttempted: v.number(),
  fgPct: v.number(),
  threePointersMade: v.number(),
  threePointersAttempted: v.number(),
  threePct: v.number(),
  freeThrowsMade: v.number(),
  freeThrowsAttempted: v.number(),
  ftPct: v.number(),
});

export const playerStatsValidator = v.object({
  _id: v.id("basketballGamePlayerStats"),
  playerId: v.id("players"),
  playerName: v.string(),
  jerseyNumber: v.optional(v.number()),
  photoUrl: v.optional(v.string()),
  clubId: v.id("clubs"),
  isStarter: v.boolean(),
  minutes: v.optional(v.number()),
  points: v.optional(v.number()),
  fieldGoalsMade: v.optional(v.number()),
  fieldGoalsAttempted: v.optional(v.number()),
  threePointersMade: v.optional(v.number()),
  threePointersAttempted: v.optional(v.number()),
  freeThrowsMade: v.optional(v.number()),
  freeThrowsAttempted: v.optional(v.number()),
  offensiveRebounds: v.optional(v.number()),
  defensiveRebounds: v.optional(v.number()),
  assists: v.optional(v.number()),
  steals: v.optional(v.number()),
  blocks: v.optional(v.number()),
  turnovers: v.optional(v.number()),
  personalFouls: v.optional(v.number()),
  plusMinus: v.optional(v.number()),
});

export const playerStatInputValidator = v.object({
  playerId: v.id("players"),
  isStarter: v.boolean(),
  minutes: v.optional(v.number()),
  points: v.optional(v.number()),
  fieldGoalsMade: v.optional(v.number()),
  fieldGoalsAttempted: v.optional(v.number()),
  threePointersMade: v.optional(v.number()),
  threePointersAttempted: v.optional(v.number()),
  freeThrowsMade: v.optional(v.number()),
  freeThrowsAttempted: v.optional(v.number()),
  offensiveRebounds: v.optional(v.number()),
  defensiveRebounds: v.optional(v.number()),
  assists: v.optional(v.number()),
  steals: v.optional(v.number()),
  blocks: v.optional(v.number()),
  turnovers: v.optional(v.number()),
  personalFouls: v.optional(v.number()),
  plusMinus: v.optional(v.number()),
});
